export const countries = [
  { code: "egy", name: "Egypt", region: "Africa", dataFile: "egy_Data.csv", resultFile: "rstar_HLW_SV_egy.csv" },
  { code: "nga", name: "Nigeria", region: "Africa", dataFile: "nga_Data.csv", resultFile: "rstar_HLW_SV_nga.csv" },
  { code: "zaf", name: "South Africa", region: "Africa", dataFile: "zaf_Data.csv", resultFile: "rstar_HLW_SV_zaf.csv" },
  { code: "bgd", name: "Bangladesh", region: "Asia and Pacific", dataFile: "bgd_Data.csv", resultFile: "rstar_HLW_SV_bgd.csv" },
  { code: "idn", name: "Indonesia", region: "Asia and Pacific", dataFile: "idn_Data.csv", resultFile: "rstar_HLW_SV_idn.csv" },
  { code: "ind", name: "India", region: "Asia and Pacific", dataFile: "ind_Data.csv", resultFile: "rstar_HLW_SV_ind.csv" },
  { code: "jpn", name: "Japan", region: "Asia and Pacific", dataFile: "jpn_Data.csv", resultFile: "rstar_HLW_SV_jpn.csv" },
  { code: "kor", name: "South Korea", region: "Asia and Pacific", dataFile: "kor_Data.csv", resultFile: "rstar_HLW_SV_kor.csv" },
  { code: "mys", name: "Malaysia", region: "Asia and Pacific", dataFile: "mys_Data.csv", resultFile: "rstar_HLW_SV_mys.csv" },
  { code: "phl", name: "Philippines", region: "Asia and Pacific", dataFile: "phl_Data.csv", resultFile: "rstar_HLW_SV_phl.csv" },
  { code: "tha", name: "Thailand", region: "Asia and Pacific", dataFile: "tha_Data.csv", resultFile: "rstar_HLW_SV_tha.csv" },
  { code: "vnm", name: "Vietnam", region: "Asia and Pacific", dataFile: "vnm_Data.csv", resultFile: "rstar_HLW_SV_vnm.csv" },
  { code: "aus", name: "Australia", region: "Asia and Pacific", dataFile: "aus_Data.csv", resultFile: "rstar_HLW_SV_aus.csv" },
  { code: "nzl", name: "New Zealand", region: "Asia and Pacific", dataFile: "nzl_Data.csv", resultFile: "rstar_HLW_SV_nzl.csv" },
  { code: "blr", name: "Belarus", region: "Europe", dataFile: "blr_Data.csv", resultFile: "rstar_HLW_SV_blr.csv" },
  { code: "cze", name: "Czech Republic", region: "Europe", dataFile: "cze_Data.csv", resultFile: "rstar_HLW_SV_cze.csv" },
  { code: "gbr", name: "United Kingdom", region: "Europe", dataFile: "gbr_Data.csv", resultFile: "rstar_HLW_SV_gbr.csv" },
  { code: "hun", name: "Hungary", region: "Europe", dataFile: "hun_Data.csv", resultFile: "rstar_HLW_SV_hun.csv" },
  { code: "nor", name: "Norway", region: "Europe", dataFile: "nor_Data.csv", resultFile: "rstar_HLW_SV_nor.csv" },
  { code: "pol", name: "Poland", region: "Europe", dataFile: "pol_Data.csv", resultFile: "rstar_HLW_SV_pol.csv" },
  { code: "rou", name: "Romania", region: "Europe", dataFile: "rou_Data.csv", resultFile: "rstar_HLW_SV_rou.csv" },
  { code: "rus", name: "Russia", region: "Europe", dataFile: "rus_Data.csv", resultFile: "rstar_HLW_SV_rus.csv" },
  { code: "srb", name: "Serbia", region: "Europe", dataFile: "srb_Data.csv", resultFile: "rstar_HLW_SV_srb.csv" },
  { code: "swe", name: "Sweden", region: "Europe", dataFile: "swe_Data.csv", resultFile: "rstar_HLW_SV_swe.csv" },
  { code: "isr", name: "Israel", region: "Middle East and Central Asia", dataFile: "isr_Data.csv", resultFile: "rstar_HLW_SV_isr.csv" },
  { code: "pak", name: "Pakistan", region: "Middle East and Central Asia", dataFile: "pak_Data.csv", resultFile: "rstar_HLW_SV_pak.csv" },
  { code: "tur", name: "Turkey", region: "Middle East and Central Asia", dataFile: "tur_Data.csv", resultFile: "rstar_HLW_SV_tur.csv" },
  { code: "bra", name: "Brazil", region: "Western Hemisphere", dataFile: "bra_Data.csv", resultFile: "rstar_HLW_SV_bra.csv" },
  { code: "can", name: "Canada", region: "Western Hemisphere", dataFile: "can_Data.csv", resultFile: "rstar_HLW_SV_can.csv" },
  { code: "chl", name: "Chile", region: "Western Hemisphere", dataFile: "chl_Data.csv", resultFile: "rstar_HLW_SV_chl.csv" },
  { code: "col", name: "Colombia", region: "Western Hemisphere", dataFile: "col_Data.csv", resultFile: "rstar_HLW_SV_col.csv" },
  { code: "cri", name: "Costa Rica", region: "Western Hemisphere", dataFile: "cri_Data.csv", resultFile: "rstar_HLW_SV_cri.csv" },
  { code: "dom", name: "Dominican Republic", region: "Western Hemisphere", dataFile: "dom_Data.csv", resultFile: "rstar_HLW_SV_dom.csv" },
  { code: "gtm", name: "Guatemala", region: "Western Hemisphere", dataFile: "gtm_Data.csv", resultFile: "rstar_HLW_SV_gtm.csv" },
  { code: "mex", name: "Mexico", region: "Western Hemisphere", dataFile: "mex_Data.csv", resultFile: "rstar_HLW_SV_mex.csv" },
  { code: "per", name: "Peru", region: "Western Hemisphere", dataFile: "per_Data.csv", resultFile: "rstar_HLW_SV_per.csv" },
  { code: "pry", name: "Paraguay", region: "Western Hemisphere", dataFile: "pry_Data.csv", resultFile: "rstar_HLW_SV_pry.csv" },
  { code: "ury", name: "Uruguay", region: "Western Hemisphere", dataFile: "ury_Data.csv", resultFile: "rstar_HLW_SV_ury.csv" },
  { code: "usa", name: "United States", region: "Western Hemisphere", dataFile: "usa_Data.csv", resultFile: "rstar_HLW_SV_us.csv" }
];

export const countryPresets = {
  us: ["usa"],
  g7: ["usa", "can", "gbr", "jpn"],
  "emerging-asia": ["bgd", "idn", "ind", "mys", "phl", "tha", "vnm"],
  clear: []
};
